name: CronVault — Backend Deploy via Jump Host
on:
  push:
    branches: [main]
    paths:
      - 'app.py'
      - 'Dockerfile'
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Backup and Prep Target Directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          proxy_host: ${{ secrets.FE_PUBLIC_IP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY_PEM }}
          host: ${{ secrets.BE_PRIVATE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY_PEM }}
          script: |
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            cp -r ~/cronvault ~/cronvault.backup.$TIMESTAMP 2>/dev/null || echo "No existing folder to backup"
            mkdir -p ~/cronvault
            ls -td ~/cronvault.backup.* 2>/dev/null | tail -n +6 | xargs -r rm -rf || true

      - name: Deploy Backend Files
        uses: appleboy/scp-action@v0.1.7
        with:
          proxy_host: ${{ secrets.FE_PUBLIC_IP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY_PEM }}
          host: ${{ secrets.BE_PRIVATE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY_PEM }}
          source: "app.py,Dockerfile,docker-compose.yml"
          target: "~/cronvault/"

      - name: Restart Backend Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          proxy_host: ${{ secrets.FE_PUBLIC_IP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY_PEM }}
          host: ${{ secrets.BE_PRIVATE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY_PEM }}
          script: |
            cd ~/cronvault
            docker compose down || true
            docker compose up -d --build
